### ISSUE TITLE
FIx closedown bug

### ISSUE THREAD

**Issue by simondelabici** [channelaccess/ca#44]
Under "certain circumstances" (Simon Ebner encountered it with the PSI snapshot application) the CA library emits "nasty messages" to the console. (I deliberately state this ticket in vague terms because currently the ticket is just a placeholder which requires more substantiation...)

This tracker is to investigate and where necessary make a fix.

**Comment by simondelabici** [comment]
Here's what the error message looks like:
```
Jul 17, 2018 6:39:35 PM org.epics.ca.impl.ContextImpl getTransport
WARNING: Failed to connect to '/129.129.130.187:5064'.
java.lang.IllegalStateException: Reactor is already shutdown.
	at org.epics.ca.impl.reactor.Reactor.register(Reactor.java:472)
	at org.epics.ca.impl.ContextImpl.getTransport(ContextImpl.java:843)
	at org.epics.ca.impl.ContextImpl.searchResponse(ContextImpl.java:774)
	at org.epics.ca.impl.ResponseHandlers.searchResponse(ResponseHandlers.java:161)
	at org.epics.ca.impl.ResponseHandlers.handleResponse(ResponseHandlers.java:80)
	at org.epics.ca.impl.BroadcastTransport.processRead(BroadcastTransport.java:163)
	at org.epics.ca.impl.BroadcastTransport.handleEvent(BroadcastTransport.java:110)
	at org.epics.ca.impl.reactor.lf.LeaderFollowersHandler.handleEvent(LeaderFollowersHandler.java:64)
	at org.epics.ca.impl.reactor.Reactor.processInternal(Reactor.java:417)
	at org.epics.ca.impl.reactor.Reactor.process(Reactor.java:294)
	at org.epics.ca.impl.reactor.lf.LeaderFollowersHandler.run(LeaderFollowersHandler.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

Jul 17, 2018 6:39:35 PM org.epics.ca.impl.BroadcastTransport processRead
SEVERE: Failed to process UDP packet.
java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.DatagramChannelImpl.ensureOpen(DatagramChannelImpl.java:323)
	at java.base/sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:332)
	at org.epics.ca.impl.BroadcastTransport.processRead(BroadcastTransport.java:134)
	at org.epics.ca.impl.BroadcastTransport.handleEvent(BroadcastTransport.java:110)
	at org.epics.ca.impl.reactor.lf.LeaderFollowersHandler.handleEvent(LeaderFollowersHandler.java:64)
	at org.epics.ca.impl.reactor.Reactor.processInternal(Reactor.java:417)
	at org.epics.ca.impl.reactor.Reactor.process(Reactor.java:294)
	at org.epics.ca.impl.reactor.lf.LeaderFollowersHandler.run(LeaderFollowersHandler.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:272)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:463)
	at org.epics.ca.impl.TCPTransport.noSyncSend(TCPTransport.java:594)
	at org.epics.ca.impl.TCPTransport.flush(TCPTransport.java:797)
	at org.epics.ca.impl.TCPTransport.flush(TCPTransport.java:754)
	at org.epics.ca.impl.TCPTransport.releaseSendBuffer(TCPTransport.java:741)
	at org.epics.ca.impl.TCPTransport.run(TCPTransport.java:841)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

Process finished with exit code 0
```
