### ISSUE TITLE
Getting Metadata for Generic (Object) Channel does not work

### ISSUE THREAD

**Issue by simongregorebner** [channelaccess/ca#7]
When trying to get more metadata to the value with an generic channel the library fails
```java
Channel<Double> channel = context.createChannel("ARIDI-PCT:CURRENT", Double.class);
channel.connectAsync().get(1, TimeUnit.SECONDS);
System.out.println(channel.get(Timestamped.class));
```

The exception thrown is:
```
Exception in thread "main" java.lang.RuntimeException: Failed to do get.
	at org.epics.ca.impl.ChannelImpl.get(ChannelImpl.java:332)
	at org.epics.ca.test.TE.main(TE.java:24)
Caused by: java.lang.RuntimeException: unsupported channel metadata type class org.epics.ca.data.Timestamped<class java.lang.Object>
	at org.epics.ca.impl.ChannelImpl.getAsync(ChannelImpl.java:346)
	at org.epics.ca.impl.ChannelImpl.get(ChannelImpl.java:330)
	... 1 more
```

Just getting the value works!
```java
System.out.println(channel.get());
```

When doing the same with a typed channel things work:
```java
Channel<Double> channel = context.createChannel("ARIDI-PCT:CURRENT", Double.class);
channel.connectAsync().get(1, TimeUnit.SECONDS);
System.out.println(channel.get(Timestamped.class));
```

**Comment by msekoranja** [comment]
Fixed.
